version: "3"
services:

  transactions-api:
    build:
      context: .
    env_file: .env
    volumes:
      - ".:/code"
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      - PYTHONIOENCODING=UTF-8
      - PYTHONUNBUFFERED=1
    command: python /code/manage.py runserver 0.0.0.0:80

  db:
    image: postgres:12
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data: {}
